from PyQt5.QtGui import *

COMMON_HEIGHT = 40
BUTTON_WIDTH = 200
BUTTON_HEIGHT = 100
BUTTON_CHANGE_WIDTH = 50
BUTTON_CHANGE_HEIGHT = 50
MARGIN = 20
WINDOW_BUTTON_NUMBER = 3
WINDOW_WIDTH = 600
WINDOW_HEIGHT = WINDOW_BUTTON_NUMBER * BUTTON_HEIGHT + (WINDOW_BUTTON_NUMBER + 1) * MARGIN
MEMORIZE_WIDTH = 1000
MEMORIZE_HEIGHT = 800
MEMORIZE_LABEL_TIME_INFO_WIDTH = 200
MEMORIZE_LABEL_BOOK_INFO_WIDTH = 300
MEMORIZE_LABEL_UNIT_INFO_WIDTH = 500
MEMORIZE_LABEL_COUNTDOWN_INFO_WIDTH = 300
MEMORIZE_LABEL_POS_INFO_WIDTH = 300


SELECT_WIDTH = 1200
SELECT_HEIGHT = 800
SELECT_LABEL_SELECT_BOOK_WIDTH = 250
SELECT_COMBOBOX_SELECT_BOOK_WIDTH = 200
SELECT_LABEL_UNIT_INFO_WIDTH = 250
SELECT_COMBOBOX_SELECT_UNIT_WIDTH = 400


ADD_WIDTH = 1200
ADD_HEIGHT = 800
ADD_LABEL_SELECT_BOOK_WIDTH = 250
ADD_COMBOBOX_SELECT_BOOK_WIDTH = 200
ADD_LABEL_UNIT_INFO_WIDTH = 240
ADD_LINEEDIT_UNIT_INFO_WIDTH = 40
ADD_LINEEDIT_UNIT_DESC_WIDTH = 300
ADD_LABEL_TIME_INFO_WIDTH = 180
ADD_LINEEDIT_TIME_INFO_WIDTH = 40


CuzFont = QFont()
CuzFont.setFamily("Microsoft YaHei")
CuzFont.setPointSize(14)

largeFont = QFont()
largeFont.setFamily("Courier New")
largeFont.setPointSize(40)

